package ar.edu.unlu.poo.modelo.enumerados;

public enum Eventos {
    REPARTIR_CARTAS_INICIALES,
    CARTAS_REPARTIDAS,
    TURNO_JUGADORES,
    EMPEZAR_TURNO_DEALER,
    CAMBIO_JUGADOR_CON_TURNO,
    RESULTADOS_OBTENIDOS,
    RE_INSCRIPCION,
    INICIA_NUEVA_RONDA,
    ACTUALIZAR_LISTA_JUGADORES,
    ACTUALIZAR_LISTA_DE_ESPERA,
    CAMBIO_ESTADO_LOBBY, MESA_ACTUALIZADA,
}
