package ar.edu.unlu.poo.modelo.enumerados;

public enum Mensajes {
    NO_QUEDAN_LUGARES,
    LA_RONDA_YA_EMPEZO,
    JUGADOR_YA_ESTA_INSCRIPTO,
    JUGADOR_YA_CONFIRMADO,
    ACCION_INVALIDA_ULTIMA_MANO,
    SALDO_INSUFICIENTE,
    DEALER_SIN_AS_PRIMERA,
    NO_ES_TURNO_INICIAL,
    ACCION_YA_REALIZADA,
    NO_CUMPLE_CONDICION_SEPARAR,
    ALGO_PASO,
    JUGADOR_EN_SALA_RONDA,
    RONDA_ACEPTANDO_INSCRIPCIONES,
    NO_ESTABA_EN_LA_LISTA_DE_ESPERA,
    UNIRSE_LISTA_ESPERA,
    JUGADOR_GUARDADO,
    NO_POSEE_DINERO_PARA_GUARDAR,
    SIN_SALDO,
    NO_NUMERICO,
    NUMERO_CORRECTO,
    ACCION_REALIZADA_EXITOSAMENTE,
    JUGADOR_YA_EN_LISTA,
    NO_ES_SU_TURNO, NO_TIENE_MAS_MANOS;
}
